version: "3"

services:

  mariadb:
    container_name : mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name : wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: on-failure
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  nginx:
    container_name : nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file: .env
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: ../volumes/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: ../volumes/mariadb

networks:
  inception:
    driver: bridge